export { default as Home } from './Home/Home'
export { default as Chat } from './Chat/Chat'
export { default as TodayPatientsList } from './TodayPatientsList/TodayPatientsList'
export { default as Statistics } from './Statistics/Statistics'
export { default as Calendar } from './Calendar/Calendar'
