export const CREATE_APPOINTMENT_NAMES = {
  SENDER: 'sender',
  PATIENT: 'patient',
  BASE_APPOINTMENT_ID: 'baseAppointmentId',
  FULL_NAME: 'fullName',
  START_DATE: 'startDate',
  END_DATE: 'endDate',
  TITLE: 'title',
  MOTIF: 'motif',
  DIAGNOSTIC: 'diagnostic',
  TREATMENT_PLAN: 'treatmentPlan',
  TOTAL_PRICE: 'totalPrice',
  PAYMENT: 'payment',
  PAYMENT_LEFT: 'paymentLeft',
  isNewTreatment: 'isNewTreatment',
  IS_CONFIRMED: 'isConfirmed',
  IS_LEFT: 'isLeft',
  IS_WAITING_ROOM: 'isWaitingRoom',
  IS_DONE: 'isDone',
}
