export const HARD_CODED_DATA = [
  {
    id: 'id-1',
    name: 'Amine Deghmine 1',
    age: '29',
    motif: 'douleur 7/10',
    state: 'très bien',
    diagnostic: 'carie entre les dents',
    treatmentPlan: 'Ipsum Dolor Sit Amet',
    history: 'Ipsum Dolor',
  },
  {
    id: 'id-2',
    name: 'Amine Deghmine 2',
    age: '29',
    motif: 'douleur 7/10',
    state: 'très bien',
    diagnostic: 'carie entre les dents',
    treatmentPlan: 'Ipsum Dolor Sit Amet',
    history: 'Ipsum Dolor',
  },
  {
    id: 'id-3',
    name: 'Amine Deghmine 3',
    age: '29',
    motif: 'douleur 7/10',
    state: 'très bien',
    diagnostic: 'carie entre les dents',
    treatmentPlan: 'Ipsum Dolor Sit Amet',
    history: 'Ipsum Dolor',
  },
  {
    id: 'id-4',
    name: 'Amine Deghmine 4',
    age: '29',
    motif: 'douleur 7/10',
    state: 'très bien',
    diagnostic: 'carie entre les dents',
    treatmentPlan: 'Ipsum Dolor Sit Amet',
    history: 'Ipsum Dolor',
  },
  {
    id: 'id-5',
    name: 'Amine Deghmine 5',
    age: '29',
    motif: 'douleur 7/10',
    state: 'très bien',
    diagnostic: 'carie entre les dents',
    treatmentPlan: 'Ipsum Dolor Sit Amet',
    history: 'Ipsum Dolor',
  },
  {
    id: 'id-6',
    name: 'Amine Deghmine 6',
    age: '29',
    motif: 'douleur 7/10',
    state: 'très bien',
    diagnostic: 'carie entre les dents',
    treatmentPlan: 'Ipsum Dolor Sit Amet',
    history: 'Ipsum Dolor',
  },
  {
    id: 'id-7',
    name: 'Amine Deghmine 7',
    age: '29',
    motif: 'douleur 7/10',
    state: 'très bien',
    diagnostic: 'carie entre les dents',
    treatmentPlan: 'Ipsum Dolor Sit Amet',
    history: 'Ipsum Dolor',
  },
]
