export const HARD_CODED_DATA = [
  {
    id: 'id-1',
    name: 'Amine Deghmine',
    age: '29',
    motif: 'douleur 3/10',
    state: 'très bien',
    diagnostic: 'carie entre les dents',
    treatmentPlan: 'Ipsum Dolor Sit Amet',
    history: 'Ipsum Dolor',
  },
  {
    id: 'id-2',
    name: 'Ahmed Boutaraa',
    age: '29',
    motif: 'douleur 5/10',
    state: 'très bien',
    diagnostic: 'carie entre les dents',
    treatmentPlan: 'Ipsum Dolor Sit Amet',
    history: 'Ipsum Dolor',
  },
  {
    id: 'id-3',
    name: 'Hamid Abd Meriem',
    age: '29',
    motif: 'douleur 7/10',
    state: 'très bien',
    diagnostic: 'carie entre les dents',
    treatmentPlan: 'Ipsum Dolor Sit Amet',
    history: 'Ipsum Dolor',
  },
  {
    id: 'id-4',
    name: 'Kamal Jamal',
    age: '29',
    motif: 'douleur 7/10',
    state: 'très bien',
    diagnostic: 'carie entre les dents',
    treatmentPlan: 'Ipsum Dolor Sit Amet',
    history: 'Ipsum Dolor',
  },
  {
    id: 'id-5',
    name: 'Walid Bensouna',
    age: '29',
    motif: 'douleur 2/10',
    state: 'très bien',
    diagnostic: 'carie entre les dents',
    treatmentPlan: 'Ipsum Dolor Sit Amet',
    history: 'Ipsum Dolor',
  },
  {
    id: 'id-6',
    name: 'Halimi Yassine',
    age: '29',
    motif: 'douleur 7/10',
    state: 'très bien',
    diagnostic: 'carie entre les dents',
    treatmentPlan: 'Ipsum Dolor Sit Amet',
    history: 'Ipsum Dolor',
  },
  {
    id: 'id-7',
    name: 'AbAlah Mejahed',
    age: '29',
    motif: 'douleur 7/10',
    state: 'très bien',
    diagnostic: 'carie entre les dents',
    treatmentPlan: 'Ipsum Dolor Sit Amet',
    history: 'Ipsum Dolor',
  },
]
