export const HARD_CODED_DATA = [
  {
    id: 'id-1',
    name: 'Amine Deghmine',
    age: '27',
    motif: 'douleur 3/10',
    state: 'très bien',
    diagnostic: 'carie entre les dents',
    treatmentPlan: 'Ipsum Dolor Sit Amet',
    history: 'Ipsum Dolor',
  },
  {
    id: 'id-2',
    name: 'Ahmed Boutaraa',
    age: '25',
    motif: 'douleur 5/10',
    state: 'très bien',
    diagnostic: 'carie entre les dents',
    treatmentPlan: 'Ipsum Dolor Sit Amet',
    history: 'Ipsum Dolor',
  },
  {
    id: 'id-3',
    name: 'Hamid Abd Meriem',
    age: '43',
    motif: 'douleur 7/10',
    state: 'très bien',
    diagnostic: 'carie entre les dents',
    treatmentPlan: 'Ipsum Dolor Sit Amet',
    history: 'Ipsum Dolor',
  },
  {
    id: 'id-4',
    name: 'Kamal Jamal',
    age: '23',
    motif: 'douleur 7/10',
    state: 'très bien',
    diagnostic: 'carie entre les dents',
    treatmentPlan: 'Ipsum Dolor Sit Amet',
    history: 'Ipsum Dolor',
  },
  {
    id: 'id-5',
    name: 'Walid Bensouna',
    age: '33',
    motif: 'douleur 2/10',
    state: 'très bien',
    diagnostic: 'carie entre les dents',
    treatmentPlan: 'Ipsum Dolor Sit Amet',
    history: 'Ipsum Dolor',
  },
  {
    id: 'id-6',
    name: 'Halimi Yassine',
    age: '19',
    motif: 'douleur 7/10',
    state: 'très bien',
    diagnostic: 'carie entre les dents',
    treatmentPlan: 'Ipsum Dolor Sit Amet',
    history: 'Ipsum Dolor',
  },
  {
    id: 'id-7',
    name: 'AbAlah Mejahed',
    age: '22',
    motif: 'douleur 7/10',
    state: 'très bien',
    diagnostic: 'carie entre les dents',
    treatmentPlan: 'Ipsum Dolor Sit Amet',
    history: 'Ipsum Dolor',
  },
]

export const AWAITINGLIST_DATA = [
  {
    id: 'id-100',
    name: 'Samir Benmahjoub',
    age: '35',
    motif: 'douleur 1/10',
    state: 'très bien',
    diagnostic: 'carie entre les dents',
    treatmentPlan: 'Ipsum Dolor Sit Amet',
    history: 'Ipsum Dolor',
  },
  {
    id: 'id-101',
    name: 'Adb Kader Lamouri',
    age: '35',
    motif: 'douleur 1/10',
    state: 'très bien',
    diagnostic: 'carie entre les dents',
    treatmentPlan: 'Ipsum Dolor Sit Amet',
    history: 'Ipsum Dolor',
  },
]
